### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by ItaniAK** [ItaniAK/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by IAM-Thirteen** [comment]
I want to open my resume and put in the intro one of the most inspirational quotes to me.

> Many of life’s failures are people who did not realize how close they were to success when they gave up.
Thomas A. Edison
