### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by ItaniAK** [ItaniAK/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by IAM-Thirteen** [comment]
## Contact information

**[email](itani.aboudi@gmail.com)**
**[facebook](https://www.facebook.com/abdulkader.itani)**
**[telegram](https://t.me/Aboudi_I)**
